### ISSUE TITLE
Not detecting scales until serial monitor is connected

### ISSUE THREAD

**Issue by whywouldi** [mp-se/kegmon#23] opened 2023-07-22 05:52 UTC
When starting up ESP-8266 or after re-booting the scales are not detected.

If I start serial monitor on laptop and re-boot the ESP-8266 the scales are detected and everything works ok.

**Comment by mp-se** [comment] 2023-07-22 18:44
That is strange, i have never had that issue. Could it be a power adapter issue ? How do you power the device ?

**Comment by whywouldi** [comment] 2023-07-23 07:42
Agreed it is a weird one. I'm currently powering via the micro-usb via either laptop or PSU. I have found powering by Micro-USB with my brewpiless keeps things more stable than via 3v3 or 5v.

The condition is totally repeatable.

**Comment by mp-se** [comment] 2023-07-23 09:29
What board are you using? Have you tested with another esp? I dont think this is software related

**Comment by whywouldi** [comment] 2023-07-23 20:00
I'm using the D1-mini. I will flash another board and report back in a day or so.

Much appreciate the guidance and the project is outstanding cheers.

**Comment by mp-se** [comment] 2023-07-23 20:21
Which hx board are you using, green, red or purple?

**Comment by whywouldi** [comment] 2023-07-23 20:30
Its the green HX711. I have a few of these too so will replace both boards and see if that fixes it.

**Comment by whywouldi** [comment] 2023-07-29 18:02
I have created a new circuit board so I can change out the D1 mini and HX711. Have tried to boards of each and the same thing. Stumped.

I will keep paying with now I have a better setup and report back if I get it going.

**Comment by mp-se** [comment] 2023-07-29 18:17
Ok, i can see if i can replicate the issue with a green board

**Comment by mp-se** [comment] 2023-07-31 07:13
I have a firmware that I use to the sensors and the hardware setup. You could install this on an esp8266 and see what the result is. I will just display the raw values on the 1st OLED screen. If you want to build it via platformIO its the hardware target. This could be extended to help check for hardware issues. 

[hw_firmware.zip](https://github.com/mp-se/kegmon/files/12212370/hw_firmware.zip)

**Comment by whywouldi** [comment] 2023-07-31 20:14
Again thanks so much for your time and help.

I have flashed the Bin file to the ESP8266:
Display show temp with live data, Scale 1 is 0, Scale 2 is 0, Raw 1 is 0 Raw 2 is 0.

After a few minutes I started serial monitor and within 5 seconds the scale 1 starts to read a value along with the temp. All others remain at 0.

This is repeatable.

**Comment by whywouldi** [comment] 2023-07-31 20:30
May have just found an article that could explain it?

https://www.esp8266.com/viewtopic.php?p=53827

I am using D3 as the data connection to the HX711. Will have to solder up a new board to try on the "scale 2 input" but unsure if that would work with the detail on the site (only one scale can be used with esp8266).

**Comment by mp-se** [comment] 2023-07-31 20:43
If you use the hx711 you can use 2 scales without probleme on esp8266, its the i2c based adc that is limited to one since the esp8266 only supports one i2c bus.

**Comment by mp-se** [comment] 2023-07-31 20:49
Can you upload a picture of your esp board? Back and front.

**Comment by mp-se** [comment] 2023-07-31 20:57
> May have just found an article that could explain it?
> 
> https://www.esp8266.com/viewtopic.php?p=53827
> 
> I am using D3 as the data connection to the HX711. Will have to solder up a new board to try on the "scale 2 input" but unsure if that would work with the detail on the site (only one scale can be used with esp8266).

I dont think this is related. If this is the case it would not boot at all. You could try to add a 3k resistor between d3 and 3v as a test. You could do the same with d4 as well. This shoudl force it to be high and not trigger the boot mode.

**Comment by whywouldi** [comment] 2023-07-31 21:48
![IMG_0004](https://github.com/mp-se/kegmon/assets/70206248/3a5cd7fc-43f4-4476-bdd8-adab1fa7cfc0)
![IMG_0003](https://github.com/mp-se/kegmon/assets/70206248/c29ac8a8-9704-4e9c-bac3-c128481f79ee)

**Comment by whywouldi** [comment] 2023-07-31 21:51
These are the two types but I have tried a couple of the v3 boards. All doing the same.

I currently have a 4k7 across D3 and 3v3. I’ve tried 4k7 across just data and data + clock all making no difference. Also good to know about two scales using the hx711 thanks.

**Comment by mp-se** [comment] 2023-08-03 07:31
I've tried to replicate your problem but on my test build it works fine- I've tested with external power supply to the 5V and both the purple and green HX boards. It boots fine and reads the data as it should

Let me know how your tests are progressing

**Comment by whywouldi** [comment] 2023-08-03 08:32
I am stumped. I Will continue to try different things and see if I can get it going.

I’m now heading out of the UK for a few weeks so will not make any progress for a while. I will report back though should I manage to sort it or fail and give up (unlikely).

As always I appreciate you taking the time to help.

cheers,

**Comment by mp-se** [comment] 2023-08-03 10:57
Do you have an esp32 s2 mini to see if that works better ?

**Comment by whywouldi** [comment] 2023-08-27 09:09
Hi, back from my vacation and I've spent this morning using a breadboard to aid testing. Following on from the gpio0 (D3) link I decided to move the scale to gpio15 (D8) & gpio14 (D5) and it was recognised. It calibrates and functions correctly every time.

Is it possible to alter the code to move scale one to D8/D5 and scale two to D3/D4? Would this be a lot of work or just on the inital pin setup? 

I dont have an ESP32 I'm afraid but I might have to get one.

**Comment by mp-se** [comment] 2023-08-28 05:39
Yes you can alter the pins in the main.hpp file and then compile your own version. 

Just make sure that you dont use the same pins for several functions.

**Comment by mp-se** [comment] 2023-08-31 19:30
Try this build, https://github.com/mp-se/kegmon/blob/dev/bin/firmware.bin

You can change pin config in the web ui. you need to reboot for it to take effect. I have just done some simple testing...

**Comment by whywouldi** [comment] 2023-09-02 10:53
Thanks so much for updating the .bin in such a short time.

I have been working with the new .bin all morning and I keep getting the same issue. when I go to the config page I get the error "unable to get data from the device". every other page works ok just the config page. Other symptoms are no detail in the new drop down boxes and inability to save with the error "Invalid ID".

I've now tried this on the original three chip and two brand new chips purchased in the hope of resolving things (all wemos D1 mini's). Note that when testing the new chips I have not connected anything to them and not even soldered the pins on the board yet the error is repeated.

sorry for the continued issues.

![image](https://github.com/mp-se/kegmon/assets/70206248/cc75fa91-0e9e-4db6-af9b-584b814ec069)

**Comment by mp-se** [comment] 2023-09-02 11:50
I know what the problem is, will fix it later today when im at a computer

**Comment by mp-se** [comment] 2023-09-02 15:01
I've checked in the fix, should be ready in a few minutes when the buiid has been completed

**Comment by whywouldi** [comment] 2023-09-02 17:17
Just uploaded, altered the pin setting, calibrated and tested. Everything is working perfectly!

Thank you so much for all the effort and time you've spent. Absolute legend.

**Closed** 2023-09-02 17:17 UTC
Labels: enhancement, investigation
